# Captain
- type: startingGear
  id: SyndicateNavalCaptainGearA
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    back: ClothingBackpackSyndicateCaptainLootA
  inhand:
    - PlasteelArmingSword

- type: startingGear
  id: SyndicateNavalCaptainGearB
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    back: ClothingBackpackSyndicateCaptainLootB
  inhand:
    - PlasteelArmingSword

- type: startingGear
  id: SyndicateNavalCaptainGearC
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    back: ClothingBackpackSyndicateCaptainLootC

- type: startingGear
  id: SyndicateNavalCaptainGearD
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    back: ClothingBackpackSyndicateCaptainLootD

# Engineer
- type: startingGear
  id: SyndicateNavalEngineerGearA
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackShotgun
    belt: ClothingBeltUtility
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    back: ClothingBackpackSyndicateEngineerLootA
  inhand:
    - ToolboxSyndicate

- type: startingGear
  id: SyndicateNavalEngineerGearB
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackShotgun
    belt: ClothingBeltUtility
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    back: ClothingBackpackSyndicateEngineerLootB
  inhand:
    - ToolboxEmergency

- type: startingGear
  id: SyndicateNavalEngineerGearC
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackShotgun
    belt: ClothingBeltUtility
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    back: ClothingBackpackSyndicateEngineerLootC
  inhand:
    - ToolboxElectrical

- type: startingGear
  id: SyndicateNavalEngineerGearD
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackShotgun
    belt: ClothingBeltUtility
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    back: ClothingBackpackSyndicateEngineerLootD
  inhand:
    - ToolboxMechanical

# Medic
- type: startingGear
  id: SyndicateNavalMedicGearA
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMedical
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackSyndicateMedicLootA
  inhand:
    - SawAdvanced

- type: startingGear
  id: SyndicateNavalMedicGearB
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMedical
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackSyndicateMedicLootB
  inhand:
    - ScalpelAdvanced

- type: startingGear
  id: SyndicateNavalMedicGearC
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMedical
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackSyndicateMedicLootC
  inhand:
    - Drill

- type: startingGear
  id: SyndicateNavalMedicGearD
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMedical
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackSyndicateMedicLootD
  inhand:
    - SawImprov

# Syndicate Second Officer
- type: startingGear
  id: SyndicateNavalSecondOfficerGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasic
  inhand:
    - WeaponAdvancedLaser

# Syndicate Security Operative
- type: startingGear
  id: SyndicateNavalOperatorGearA
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicateOperativeLootA
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackSMG
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - KukriKnife

- type: startingGear
  id: SyndicateNavalOperatorGearB
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicateOperativeLootB
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackSMG
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - KukriKnife

- type: startingGear
  id: SyndicateNavalOperatorGearC
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicateOperativeLootC
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackSMG
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - Machete

- type: startingGear
  id: SyndicateNavalOperatorGearD
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicateOperativeLootD
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackSMG
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - CombatKnife

# Syndicate Grenadier
- type: startingGear
  id: SyndicateNavalGrenadierGear
  equipment:
    head: ClothingHeadHelmetBombSuit
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateRed
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackChinaLake
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterSuitBomb

# Syndicate Saboteur
- type: startingGear
  id: SyndicateNavalSaboteurGearA
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPistol
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSyndicateSaboteurLootA
  inhand:
    - CombatKnife

- type: startingGear
  id: SyndicateNavalSaboteurGearB
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPistol
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSyndicateSaboteurLootB
  inhand:
    - CombatKnife

- type: startingGear
  id: SyndicateNavalSaboteurGearC
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPistol
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSyndicateSaboteurLootC
  inhand:
    - CombatKnife

- type: startingGear
  id: SyndicateNavalSaboteurGearD
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPistol
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSyndicateSaboteurLootD
  inhand:
    - CombatKnife

# Syndicate Victim: Driven Insane Victim of Experimentation
- type: startingGear
  id: SyndicateVictimInsaneGear
  equipment:
    outerClothing: ClothingOuterHospitalGown
    mask: ClothingMaskMuzzle
    neck: ClothingNeckHeadphones
  inhand:
    - ReinforcedShiv

# Syndicate Commander
- type: startingGear
  id: SyndicateNavalCommanderGearA # Megafauna for dungeons
  equipment:
    mask: ClothingMaskGasSyndicate
    neck: BedsheetSyndie
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterHardsuitSyndieEliteUnremoveable
    head: ClothingHeadHelmetHardsuitSyndieEliteUnremoveable
    gloves: ClothingHandsGlovesColorBlackAK
    shoes: ClothingShoesBootsMagSyndie
    back: ClothingBackpackSyndicateCommanderLootA
  inhand:
    - CaptainSabre

- type: startingGear
  id: SyndicateNavalCommanderGearB
  equipment:
    mask: ClothingMaskGasSyndicate
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterHardsuitSyndieEliteUnremoveable
    head: ClothingHeadHelmetHardsuitSyndieEliteUnremoveable
    gloves: ClothingHandsGlovesColorBlackAK
    shoes: ClothingShoesBootsMagSyndie
    back: ClothingBackpackSyndicateCommanderLootB
  inhand:
    - CaptainSabre

- type: startingGear
  id: SyndicateNavalCommanderGearC
  equipment:
    mask: ClothingMaskGasSyndicate
    neck: BedsheetSyndie
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterHardsuitSyndieBloodRedUnremoveable
    head: ClothingHeadHelmetHardsuitSyndieUnremoveable
    gloves: ClothingHandsGlovesColorBlackAK
    shoes: ClothingShoesBootsMagSyndie
    back: ClothingBackpackSyndicateCommanderLootC
  inhand:
    - CaptainSabre

- type: startingGear
  id: SyndicateNavalCommanderGearD
  equipment:
    mask: ClothingMaskGasSyndicate
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterHardsuitSyndieBloodRedUnremoveable
    head: ClothingHeadHelmetHardsuitSyndieUnremoveable
    gloves: ClothingHandsGlovesColorBlackAK
    shoes: ClothingShoesBootsMagSyndie
    back: ClothingBackpackSyndicateCommanderLootD
  inhand:
    - CaptainSabre

# Syndicate Deckhand
- type: startingGear
  id: SyndicateNavalDeckhandGearA
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlackPistol
    back: ClothingBackpackSyndicateDeckhandLootA
  inhand:
    - CrowbarRed

- type: startingGear
  id: SyndicateNavalDeckhandGearB
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlackPistol
    back: ClothingBackpackSyndicateDeckhandLootB
  inhand:
    - Crowbar

- type: startingGear
  id: SyndicateNavalDeckhandGearC
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlackPistol
    back: ClothingBackpackSyndicateDeckhandLootC
  inhand:
    - Wrench

- type: startingGear
  id: SyndicateNavalDeckhandGearD
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlackPistol
    back: ClothingBackpackSyndicateDeckhandLootD
  inhand:
    - Screwdriver

# Syndicate Mime
- type: startingGear
  id: SyndicateNavalMimeGear
  equipment:
    head: ClothingHeadHatBeret
    mask: ClothingMaskMime
    neck: ClothingNeckScarfStripedSyndieRed
    jumpsuit: ClothingUniformJumpsuitMime
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorBulletproof
    belt: ClothingBeltSyndieHolster
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackMessengerSyndicate
    pocket1: Stimpack
  inhand:
    - Chainsaw

# Syndicate Chemwarrior
- type: startingGear
  id: SyndicateNavalChemwarriorGear
  equipment:
    head: ClothingHeadHatHoodBioArmoredSyndicate
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateRed
    gloves: ClothingHandsGlovesColorBlackSprayNozzle
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterBioArmoredSyndicate
    belt: ClothingBeltSyndieHolster
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackWaterTank
    pocket1: Stimpack
  inhand:
    - Machete
