# Captain
- type: startingGear
  id: SyndicateNavalCaptainGear
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
#    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
#    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltSyndieHolster
    ears: ClothingHeadsetAltSyndicate
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    pocket1: WeaponRevolverPythonAP
  inhand:
    - CaptainSabre
#    - WeaponRevolverPythonAP

# Engineer
- type: startingGear
  id: SyndicateNavalEngineerGear
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    back: ClothingBackpackDuffelSyndicateAmmo
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    belt: ClothingBeltUtility
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    pocket1: MagazineShotgun
    pocket2: MagazineShotgun
  inhand:
    - WeaponShotgunBulldog
#    - ToolboxSyndicate

# Medic
- type: startingGear
  id: SyndicateNavalMedicGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    back: ClothingBackpackDuffelSyndicateMedical
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    belt: ClothingBeltMedical
    ears: ClothingHeadsetAltSyndicate
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
  inhand:
#    - DartSindicateTranquilizer
    - SawAdvanced

# Syndicate Deckhand
- type: startingGear
  id: SyndicateNavalDeckhandGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltMilitaryWebbing
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasic
  inhand:
    - WeaponAdvancedLaser
#    - KukriKnife

# Syndicate Security Operative
- type: startingGear
  id: SyndicateNavalOperatorGear
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: WeaponSubMachineGunAtreides
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    belt: ClothingBeltMilitaryWebbing
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - KukriKnife
#    - WeaponSubMachineGunAtreides
#    - RiotShield

# Syndicate Grenadier
- type: startingGear
  id: SyndicateNavalGrenadierGear
  equipment:
    head: ClothingHeadHelmetBombSuit
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    belt: ClothingBeltMilitaryWebbing
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterSuitBomb
    pocket1: GrenadeFrag
    pocket2: GrenadeFrag
  inhand:
    - WeaponLauncherChinaLake
#    - WeaponSubMachineGunAtreides
#    - RiotShield

# Syndicate Saboteur
- type: startingGear
  id: SyndicateNavalSaboteurGear
  equipment:
    head: ClothingHeadHatSyndie
    back: JetpackBlackFilled
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
#    id: SyndiPDA # Shouldn't spawn it
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
    pocket1: WeaponPistolViper
  inhand:
    - CombatKnife

# Syndicate Victim: Driven Insane Victim of Experimentation
- type: startingGear
  id: SyndicateVictimInsaneGear
  equipment:
    outerClothing: ClothingOuterHospitalGown
    mask: ClothingMaskMuzzle
    neck: ClothingNeckHeadphones
  inhand:
    - ReinforcedShiv
#    - ReinforcedShiv
