#region T1 apprentice

#region T2 adept
- type: startingGear
  id: NPCWizardAdeptBlueGear
  equipment:
    head: ClothingHeadHatHoodTacticalWizardBlue
    shoes: ClothingShoesWizard
    belt: ClothingBeltWizardBlue
    outerClothing: ClothingOuterRobeTacticalWizardBlue
    mask: ClothingMaskWizardBlue
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponInertStaffWizardElementalAdept

#region T3 master
- type: startingGear
  id: NPCWizardMasterBlueGear
  equipment:
    head: ClothingHeadHatHoodTacticalWizardBlue
    shoes: ClothingShoesWizard
    belt: ClothingBeltWizardBlue
    neck: ClothingNeckScarfWizardBlue
    outerClothing: ClothingOuterRobeTacticalWizardBlue
    mask: ClothingMaskWizardBlue
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponInertStaffWizardLightningAdept

# Wizard
- type: startingGear
  id: NPCWizardBlueGear
  equipment:
    head: ClothingHeadHatHoodTacticalWizardBlue
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterWizard
  inhand:
    - WeaponInertStaffWizardElementalAdept

- type: startingGear
  id: NPCWizardRedGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWizardRed
  inhand:
    - WeaponInertStaffWizardBoltFireAdept

- type: startingGear
  id: NPCWizardVioletGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWizardViolet
  inhand:
    - WeaponInertStaffWizardBoltMagicAdept

- type: startingGear
  id: NPCWizardSoapGear
  equipment:
    head: ClothingHeadHatRedwizard
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    outerClothing: ClothingOuterClownPriest
    pocket1: BikeHorn
  inhand:
     - WeaponInertStaffWizardSoapAdept

- type: startingGear
  id: NPCWizardBrickGear
  equipment:
    head: ClothingHeadHatBrickwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    # neck: ClothingNeckScarfStripedRed - Does not need neck slot
    outerClothing: ClothingOuterWizardBrick
  inhand:
    - WeaponInertStaffWizardBrickAdept

# Hardsuits
- type: startingGear
  id: NPCWizardBlueHardsuitGear
  equipment:
    head: ClothingHeadHelmetWizardHelm
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterArmorMagusblue # Well, it's not a hardsuit but whatever
  inhand:
    - WeaponInertStaffWizardElementalAdept

- type: startingGear
  id: NPCWizardRedHardsuitGear
  equipment:
    head: ClothingHeadHelmetWizardHelm
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterArmorMagusred # Well, it's not a hardsuit but whatever
  inhand:
    - WeaponInertStaffWizardBoltFireAdept

- type: startingGear
  id: NPCWizardVioletHardsuitGear
  equipment:
    head: ClothingHeadHelmetWizardHelm
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard
  inhand:
    - WeaponInertStaffWizardBoltMagicAdept

- type: startingGear
  id: NPCWizardSoapHardsuitGear
  equipment:
    head: ClothingHeadHelmetWizardHelm
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterHardsuitClown
  inhand:
    - WeaponInertStaffWizardSoapAdept

- type: startingGear
  id: NPCWizardBrickHardsuitGear
  equipment:
    head: ClothingHeadHelmetHardsuitWizardBrick
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    outerClothing: ClothingOuterHardsuitWizardBrick
  inhand:
    - WeaponInertStaffWizardBrickAdept
