# Blue Wizard
- type: startingGear
  id: NPCWizardBlueGear
  equipment:
    head: ClothingHeadHatWizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterWizard

# Red Wizard
- type: startingGear
  id: NPCWizardRedGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWizardRed

# Violet (yup, that's how this color is called, sure, ok) Wizard
- type: startingGear
  id: NPCWizardVioletGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWizardViolet

# Wizard Hardsuit
- type: startingGear
  id: NPCWizardHardsuitGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard

# Wizard Soap
- type: startingGear
  id: NPCWizardSoapGear
  equipment:
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    outerClothing: ClothingOuterClownPriest
    pocket1: BikeHorn
#  inhand:
#    - ToyHammer
