# Wizard
- type: startingGear
  id: NPCWizardBlueGear
  equipment:
    head: ClothingHeadHatWizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterWizard
  inhand:
    - WizardStaffMeleeBase

- type: startingGear
  id: NPCWizardRedGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWizardRed
  inhand:
    - WizardStaffMeleeRed

- type: startingGear
  id: NPCWizardVioletGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWizardViolet
  inhand:
    - WizardStaffMeleeViolet

# Hardsuits
- type: startingGear
  id: NPCWizardBlueHardsuitGear
  equipment:
    head: ClothingHeadHatWizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterHardsuitWizard
  inhand:
    - WizardStaffMeleeBase

- type: startingGear
  id: NPCWizardRedHardsuitGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterHardsuitWizard
  inhand:
    - WizardStaffMeleeRed

- type: startingGear
  id: NPCWizardVioletHardsuitGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard
  inhand:
    - WizardStaffMeleeViolet

# Wizard Soap
- type: startingGear
  id: NPCWizardSoapGear
  equipment:
    head: ClothingHeadHatRedwizard
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    outerClothing: ClothingOuterClownPriest
    pocket1: BikeHorn
  inhand:
#    - ToyHammer
     - WizardStaffMeleeSoap
#    - Katana