# Wizard
- type: startingGear
  id: NPCWizardBlueGear
  equipment:
    head: ClothingHeadHatWizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterWizard

- type: startingGear
  id: NPCWizardRedGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: NPCWizardVioletGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWizardViolet

# Hardsuits
- type: startingGear
  id: NPCWizardBlueHardsuitGear
  equipment:
    head: ClothingHeadHatWizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard

- type: startingGear
  id: NPCWizardRedHardsuitGear
  equipment:
    head: ClothingHeadHatRedwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard

- type: startingGear
  id: NPCWizardVioletHardsuitGear
  equipment:
    head: ClothingHeadHatVioletwizard
    shoes: ClothingShoesWizard
    belt: ClothingBeltWand
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterHardsuitWizard

# Wizard Soap
- type: startingGear
  id: NPCWizardSoapGear
  equipment:
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    outerClothing: ClothingOuterClownPriest
    pocket1: BikeHorn
#  inhand:
#    - ToyHammer
